export const foods = [
  {
    id: 1,
    name: 'ひじきご飯',
    price: 410,
    priceAll: 410,
    count: 1,
    limit: '5年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.alpha-online.jp/items/166',
  },
  {
    id: 2,
    name: 'しょうがご飯',
    price: 410,
    priceAll: 410,
    count: 1,
    limit: '5年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.alpha-online.jp/items/165',
  },
  {
    id: 3,
    name: '舞茸と根菜のおこわ',
    price: 410,
    priceAll: 410,
    count: 1,
    limit: '5年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.alpha-online.jp/items/164',
  },
  {
    id: 4,
    name: '五目ご飯',
    price: 410,
    priceAll: 410,
    count: 1,
    limit: '5年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.alpha-online.jp/items/162',
  },
  {
    id: 5,
    name: '山菜おこわ',
    price: 410,
    priceAll: 410,
    count: 1,
    limit: '5年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.alpha-online.jp/items/160',
  },
  {
    id: 6,
    name: 'ドライカレー',
    price: 410,
    priceAll: 410,
    count: 1,
    limit: '5年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.alpha-online.jp/items/159',
  },
  {
    id: 7,
    name: '野菜ピラフ',
    price: 410,
    priceAll: 410,
    count: 1,
    limit: '5年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.alpha-online.jp/items/158',
  },
  {
    id: 8,
    name: 'とうもろこしご飯',
    price: 410,
    priceAll: 410,
    count: 1,
    limit: '5年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.alpha-online.jp/items/155',
  },
  {
    id: 9,
    name: '白飯',
    price: 324,
    priceAll: 324,
    count: 1,
    limit: '5年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.alpha-online.jp/items/163',
  },
  {
    id: 10,
    name: '白がゆ',
    price: 302,
    priceAll: 302,
    count: 1,
    limit: '5年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.alpha-online.jp/items/157',
  },
  {
    id: 11,
    name: '梅がゆ',
    price: 334,
    priceAll: 334,
    count: 1,
    limit: '5年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.alpha-online.jp/items/156',
  },
  {
    id: 12,
    name: 'わかめご飯',
    price: 378,
    priceAll: 378,
    count: 1,
    limit: '5年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.alpha-online.jp/items/161',
  },
  {
    id: 13,
    name: '安心米おこげ（ぜんざい）',
    price: 432,
    priceAll: 432,
    count: 1,
    limit: '7年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: true,
    url: 'https://www.alpha-online.jp/items/154',
  },
  {
    id: 14,
    name: '安心米おこげ（カレー）',
    price: 324,
    priceAll: 324,
    count: 1,
    limit: '7年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: true,
    url: 'https://www.alpha-online.jp/items/153',
  },
  {
    id: 15,
    name: '安心米おこげ（コンソメ）',
    price: 324,
    priceAll: 324,
    count: 1,
    limit: '7年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: true,
    url: 'https://www.alpha-online.jp/items/152',
  },
  {
    id: 16,
    name: '安心米おこげ（梅味）',
    price: 324,
    priceAll: 324,
    count: 1,
    limit: '7年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: true,
    url: 'https://www.alpha-online.jp/items/151',
  },
  {
    id: 17,
    name: 'ぜんざいおはぎ',
    price: 324,
    priceAll: 324,
    count: 1,
    limit: '7年',
    allergy: '',
    genre: 'お菓子',
    isOnly: true,
    url: 'https://www.alpha-online.jp/items/139',
  },
  {
    id: 18,
    name: '白がゆ（レトルト）',
    price: 291,
    priceAll: 291,
    count: 1,
    limit: '7年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: true,
    url: 'https://www.alpha-online.jp/items/140',
  },
  {
    id: 19,
    name: '洋風とり雑炊（大缶）',
    price: 9720,
    priceAll: 9720,
    count: 1,
    limit: '25年',
    allergy: '小麦,大豆,鶏肉,ゼラチン',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.seishop.jp/view/item/000000000953',
  },
  {
    id: 20,
    name: '洋風えび雑炊（大缶）',
    price: 9720,
    priceAll: 9720,
    count: 1,
    limit: '25年',
    allergy: 'えび,小麦,乳,大豆,鶏肉,ゼラチン',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.seishop.jp/view/item/000000000954',
  },
  {
    id: 21,
    name: '洋風とり雑炊（小缶）',
    price: 3780,
    priceAll: 3780,
    count: 1,
    limit: '25年',
    allergy: '小麦,大豆,鶏肉,ゼラチン',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.seishop.jp/view/item/000000000955',
  },
  {
    id: 22,
    name: '洋風えび雑炊（小缶）',
    price: 3780,
    priceAll: 3780,
    count: 1,
    limit: '２５年',
    allergy: 'えび,小麦,乳,大豆,鶏肉,ゼラチン',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.seishop.jp/view/item/000000000956',
  },
  {
    id: 23,
    name: '和風鯛ごはん６食セット',
    price: 561.5,
    priceAll: 3369,
    count: 6,
    limit: '７年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: true,
    url: 'https://okadayabousai-select.com/SHOP/HZS024.html',
  },
  {
    id: 24,
    name: '野菜ごはん６食セット',
    price: 561.5,
    priceAll: 3369,
    count: 6,
    limit: '７年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: true,
    url: 'https://okadayabousai-select.com/SHOP/HZS046.html',
  },
  {
    id: 25,
    name: '五目ごはん６食セット',
    price: 561.5,
    priceAll: 3369,
    count: 6,
    limit: '７年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: true,
    url: 'https://okadayabousai-select.com/SHOP/HZS030.html',
  },
  {
    id: 26,
    name: 'えいようかん',
    price: 129.6,
    priceAll: 648,
    count: 5,
    limit: '５年６ヶ月',
    allergy: '',
    genre: 'お菓子',
    isOnly: true,
    url: 'https://www.imuraya-webshop.jp/shop/g/gJA1116600190S/',
  },
  {
    id: 27,
    name: '100g尾西の白飯',
    price: 324,
    priceAll: 324,
    count: 1,
    limit: '５年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.onisifoods.co.jp/products/hakuhan.html',
  },
  {
    id: 28,
    name: '100g尾西のアレルギー対応五目ごはん',
    price: 410,
    priceAll: 410,
    count: 1,
    limit: '５年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.onisifoods.co.jp/products/gomoku_allergy.html',
  },
  {
    id: 29,
    name: '100g尾西のわかめごはん',
    price: 378,
    priceAll: 378,
    count: 1,
    limit: '５年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.onisifoods.co.jp/products/wakame.html',
  },
  {
    id: 30,
    name: '100g尾西のきのこごはん',
    price: 410,
    priceAll: 410,
    count: 1,
    limit: '５年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.onisifoods.co.jp/products/inaka.html',
  },
  {
    id: 31,
    name: '100g尾西のたけのこごはん',
    price: 410,
    priceAll: 410,
    count: 1,
    limit: '５年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.onisifoods.co.jp/products/takenoko.html',
  },
  {
    id: 32,
    name: '100g尾西の三菜おこわ',
    price: 453,
    priceAll: 453,
    count: 1,
    limit: '５年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.onisifoods.co.jp/products/sansai.html',
  },
  {
    id: 33,
    name: '100g尾西の赤飯',
    price: 410,
    priceAll: 410,
    count: 1,
    limit: '５年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.onisifoods.co.jp/products/sekihan.html',
  },
  {
    id: 34,
    name: '100g尾西のドライカレー',
    price: 410,
    priceAll: 410,
    count: 1,
    limit: '５年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.onisifoods.co.jp/products/drycurry.html',
  },
  {
    id: 35,
    name: '100g尾西の五目ごはん',
    price: 410,
    priceAll: 410,
    count: 1,
    limit: '５年',
    allergy: '小麦、大豆',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.onisifoods.co.jp/products/gomoku.html',
  },
  {
    id: 36,
    name: '100g尾西の松茸ごはん',
    price: 475,
    priceAll: 475,
    count: 1,
    limit: '５年',
    allergy: '小麦、大豆、乳、まつたけ',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.onisifoods.co.jp/products/matsutake.html',
  },
  {
    id: 37,
    name: '100g尾西のチキンライス',
    price: 410,
    priceAll: 410,
    count: 1,
    limit: '５年',
    allergy: '小麦、大豆、鶏肉、豚肉',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.onisifoods.co.jp/products/chickenrice.html',
  },
  {
    id: 38,
    name: '100g尾西のえびピラフ',
    price: 453,
    priceAll: 453,
    count: 1,
    limit: '５年',
    allergy: 'えび、かに、小麦、大豆、乳、豚肉、鶏肉、ゼラチン',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.onisifoods.co.jp/products/ebipilaf.html',
  },
  {
    id: 39,
    name: '貝柱のおかゆ（レトルト）',
    price: 356,
    priceAll: 356,
    count: 1,
    limit: '７年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: true,
    url: 'https://www.alpha-online.jp/items/91',
  },
  {
    id: 40,
    name: '野菜カレースープ',
    price: 540,
    priceAll: 540,
    count: 1,
    limit: '５年',
    allergy: '',
    genre: 'スープ類',
    isOnly: true,
    url: 'https://www.alpha-online.jp/items/150',
  },
  {
    id: 41,
    name: 'ミネストローネ',
    price: 540,
    priceAll: 540,
    count: 1,
    limit: '５年',
    allergy: '',
    genre: 'スープ類',
    isOnly: true,
    url: 'https://www.alpha-online.jp/items/149',
  },
  {
    id: 42,
    name: '和風五目スープ',
    price: 540,
    priceAll: 540,
    count: 1,
    limit: '５年',
    allergy: '',
    genre: 'スープ類',
    isOnly: true,
    url: 'https://www.alpha-online.jp/items/148',
  },
  {
    id: 43,
    name: '安心米クイック五目ご飯',
    price: 378,
    priceAll: 378,
    count: 1,
    limit: '５年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.alpha-online.jp/items/144',
  },
  {
    id: 44,
    name: '安心米クイックドライカレー',
    price: 388,
    priceAll: 388,
    count: 1,
    limit: '５年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.alpha-online.jp/items/143',
  },
  {
    id: 45,
    name: '安心米クイック白飯',
    price: 302,
    priceAll: 302,
    count: 1,
    limit: '５年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.alpha-online.jp/items/142',
  },
  {
    id: 46,
    name: '安心米クイックわかめご飯',
    price: 356,
    priceAll: 356,
    count: 1,
    limit: '５年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.alpha-online.jp/items/141',
  },
  {
    id: 47,
    name: '42g白がゆ',
    price: 302,
    priceAll: 302,
    count: 1,
    limit: '５年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.onisifoods.co.jp/products/shirogayu.html',
  },
  {
    id: 48,
    name: '42g梅がゆ',
    price: 334,
    priceAll: 334,
    count: 1,
    limit: '５年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.onisifoods.co.jp/products/umegayu.html',
  },
  {
    id: 49,
    name: '42g塩こんぶがゆ',
    price: 334,
    priceAll: 334,
    count: 1,
    limit: '５年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://www.onisifoods.co.jp/products/shiokonbugayu.html',
  },
  {
    id: 50,
    name: 'フルーツドロップ',
    price: 270,
    priceAll: 270,
    count: 1,
    limit: '５年',
    allergy: '',
    genre: 'お菓子',
    isOnly: true,
    url: 'https://izameshi.com/fruit-drop/',
  },
  {
    id: 51,
    name: 'もち六年',
    price: 540,
    priceAll: 540,
    count: 1,
    limit: '６年半',
    allergy: '大豆',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://unique-sb.co.jp/product/mochi-rokunen-new/',
  },
  {
    id: 53,
    name: '缶入カンパン',
    price: 262.4166666666667,
    priceAll: 6298,
    count: 24,
    limit: '５年６ヶ月',
    allergy: '乳,小麦,ごま,大豆',
    genre: 'パン類',
    isOnly: true,
    url: 'https://shop.bourbon.jp/products/detail/KA-35016',
  },
  {
    id: 54,
    name: '富士ミネラルウォーター',
    price: 486,
    priceAll: 2916,
    count: 6,
    limit: '５年',
    allergy: '',
    genre: '水',
    isOnly: false,
    url: 'https://saiboupark.jp/products/detail/122',
  },
  {
    id: 55,
    name: '霧島湧水 志布志の水',
    price: 150,
    priceAll: 150,
    count: 1,
    limit: '５年',
    allergy: '',
    genre: '水',
    isOnly: false,
    url: 'https://www.kirishima-yuusui.jp/shibushi_water',
  },
  {
    id: 56,
    name: 'サーフビバレッジ 自然水',
    price: 82.5,
    priceAll: 1980,
    count: 24,
    limit: '２年',
    allergy: '',
    genre: '水',
    isOnly: false,
    url: 'https://surf-bev.com/lineup/shizensui/',
  },
  {
    id: 57,
    name: '５年保存水',
    price: 162,
    priceAll: 3888,
    count: 24,
    limit: '５年',
    allergy: '',
    genre: '水',
    isOnly: false,
    url: 'https://www.pro-bousai.jp/shop/shopdetail.html?brandcode=000000000011&search=%A3%B5%C7%AF%CA%DD%C2%B8%BF%E5&sort=',
  },
  {
    id: 58,
    name: 'アコール１０年保存水',
    price: 300,
    priceAll: 3600,
    count: 12,
    limit: '１０年',
    allergy: '',
    genre: '水',
    isOnly: false,
    url: 'https://akol.jp/c/item-list/stockwater/10118',
  },
  {
    id: 59,
    name: '純天然アルカリ保存水',
    price: 340.1666666666667,
    priceAll: 2041,
    count: 6,
    limit: '７年',
    allergy: '',
    genre: '水',
    isOnly: false,
    url: 'https://www.kanaginohana.com/hozon/',
  },
  {
    id: 60,
    name: 'おいしい水 天然水 長期保存水',
    price: 160,
    priceAll: 160,
    count: 1,
    limit: '６年',
    allergy: '',
    genre: '水',
    isOnly: false,
    url: 'https://www.asahiinryo.co.jp/products/water/oisgiimizu-tyoukihozon/',
  },
  {
    id: 61,
    name: 'カムイワッカ 麗水',
    price: 567,
    priceAll: 3402,
    count: 6,
    limit: '１５年',
    allergy: '',
    genre: '水',
    isOnly: false,
    url: 'https://store.shopping.yahoo.co.jp/jm-ns/',
  },
  {
    id: 62,
    name: '赤穂化成 備蓄水',
    price: 121.41666666666667,
    priceAll: 2914,
    count: 24,
    limit: '５年',
    allergy: '',
    genre: '水',
    isOnly: false,
    url: 'https://akol.jp/c/item-list/stockwater/10167',
  },
  {
    id: 63,
    name: '山梨天然水ラベルレス保存水',
    price: 97.95833333333333,
    priceAll: 2351,
    count: 24,
    limit: '５年',
    allergy: '',
    genre: '水',
    isOnly: false,
    url: 'https://daianshin.com/SHOP/101030.html',
  },
  {
    id: 64,
    name: 'アイリスの保存水',
    price: 83.33333333333333,
    priceAll: 2000,
    count: 24,
    limit: '５年',
    allergy: '',
    genre: '水',
    isOnly: false,
    url: 'https://www.irisplaza.co.jp/index.php?KB=SHOSAI&SID=H574411',
  },
  {
    id: 65,
    name: '吉野家 缶飯牛丼',
    price: 810,
    priceAll: 4860,
    count: 6,
    limit: '3年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://e-shop.yoshinoya.com/shop/g/g666198/',
  },
  {
    id: 66,
    name: '吉野家 缶飯焼鶏',
    price: 810,
    priceAll: 4860,
    count: 6,
    limit: '3年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://e-shop.yoshinoya.com/shop/g/g666202/',
  },
  {
    id: 67,
    name: '吉野家 缶飯豚丼',
    price: 810,
    priceAll: 4860,
    count: 6,
    limit: '3年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://e-shop.yoshinoya.com/shop/g/g666372/',
  },
  {
    id: 68,
    name: '吉野家 缶飯塩さば丼',
    price: 810,
    priceAll: 4860,
    count: 6,
    limit: '3年',
    allergy: '',
    genre: 'ご飯類',
    isOnly: false,
    url: 'https://e-shop.yoshinoya.com/shop/g/g666203/',
  },
  {
    id: 69,
    name: 'たべっ子どうぶつビスケット',
    price: 475,
    priceAll: 475,
    count: 1,
    limit: '５年',
    allergy: '小麦、大豆、乳',
    genre: 'お菓子',
    isOnly: true,
    url: 'https://murokanamono.com/item-detail/997984',
  },
  {
    id: 70,
    name: 'ビスコ保存缶',
    price: 536.8,
    priceAll: 5368,
    count: 10,
    limit: '５年',
    allergy: '',
    genre: 'お菓子',
    isOnly: true,
    url: 'https://shop.glico.com/pages/food-gift-kashi-icecream-item-6731460/',
  },
  {
    id: 71,
    name: 'ルヴァンプライムクラッカー',
    price: 489,
    priceAll: 489,
    count: 1,
    limit: '５年',
    allergy: '小麦',
    genre: 'お菓子',
    isOnly: true,
    url: 'https://store.shopping.yahoo.co.jp/soukai/4903015110381.html?sc_e=slga_pla_i_shp_02498&gbraid=0AAAAAC2i689aam1qBYqZT-vHsXgQjt6vw&gclid=EAIaIQobChMI3cTr7urUgwMVW9gWBR3mfQVgEAQYBCABEgJiU_D_BwE',
  },
  {
    id: 72,
    name: 'ミルクスティック',
    price: 324,
    priceAll: 324,
    count: 1,
    limit: '５年',
    allergy: '乳',
    genre: 'お菓子',
    isOnly: true,
    url: 'https://www.onisifoods.co.jp/products/milkstick.html',
  },
  {
    id: 73,
    name: 'ハーベスト保存缶',
    price: 432,
    priceAll: 432,
    count: 1,
    limit: '５年',
    allergy: '小麦、乳',
    genre: 'お菓子',
    isOnly: true,
    url: 'https://www.google.com/search?q=%E6%9D%B1%E3%83%8F%E3%83%88+%E3%83%8F%E3%83%BC%E3%83%99%E3%82%B9%E3%83%88+%E9%9D%9E%E5%B8%B8%E9%A3%9F&ie=UTF-8&oe=UTF-8&hl=ja-jp&client=safari#oshopproduct=pid:9202178481827419655,oid:9202178481827419655,iid:16430557494733294127,pvt:hg,pvo:3&oshop=apv&pvs=0',
  },
  {
    id: 74,
    name: 'ライスクッキー（ココナッツ）',
    price: 130,
    priceAll: 130,
    count: 1,
    limit: '５年',
    allergy: '',
    genre: 'お菓子',
    isOnly: true,
    url: 'https://item.rakuten.co.jp/auc-super-ism77/ecoeat_742/?scid=af_sp_etc&sc2id=af_117_0_10002089',
  },
  {
    id: 75,
    name: 'パイン飴保存缶',
    price: 486,
    priceAll: 486,
    count: 1,
    limit: '５年',
    allergy: '',
    genre: 'お菓子',
    isOnly: true,
    url: 'https://pineame.net/items/5668e0573bcba9a37d003a1e',
  },
  {
    id: 76,
    name: 'マリービスケット',
    price: 324,
    priceAll: 324,
    count: 1,
    limit: '６年',
    allergy: '小麦、大豆、乳',
    genre: 'お菓子',
    isOnly: true,
    url: 'https://www.morinaga.co.jp/public/newsrelease/web/fix/file6013995333362.pdf',
  },
  {
    id: 77,
    name: 'スーパーバランス',
    price: 378,
    priceAll: 378,
    count: 1,
    limit: '６年',
    allergy: '小麦、大豆、乳、卵、ゼラチン',
    genre: 'お菓子',
    isOnly: true,
    url: 'https://unique-sb.co.jp/product/super-balance/',
  },
  {
    id: 78,
    name: '揚げ入りさぬきうどん',
    price: 800,
    priceAll: 800,
    count: 1,
    limit: '５年',
    allergy: '小麦、乳、大豆',
    genre: '麺類',
    isOnly: true,
    url: 'https://www.konpiraya.jp/shopdetail/000000000045/',
  },
  {
    id: 79,
    name: '即席うどん',
    price: 594,
    priceAll: 594,
    count: 1,
    limit: '　　　　　　3年',
    allergy: '小麦,大豆',
    genre: '麺類',
    isOnly: false,
    url: '',
  },
  {
    id: 80,
    name: 'その場　deパスタ（トマト）',
    price: 388.8,
    priceAll: 19440,
    count: 50,
    limit: '5年',
    allergy: '小麦',
    genre: '麺類',
    isOnly: false,
    url: 'https://ec.midori-anzen.com/shop/g/g4082119310/',
  },
  {
    id: 81,
    name: 'その場　deパスタ（コーンクリーム）',
    price: 388.8,
    priceAll: 19440,
    count: 50,
    limit: '5年',
    allergy: '小麦,大豆',
    genre: '麺類',
    isOnly: false,
    url: 'https://ec.midori-anzen.com/shop/g/g4082119311/',
  },
  {
    id: 82,
    name: 'その場　deパスタ（和風）',
    price: 388.8,
    priceAll: 19440,
    count: 50,
    limit: '5年',
    allergy: '小麦,大豆',
    genre: '麺類',
    isOnly: false,
    url: 'https://ec.midori-anzen.com/shop/g/g4082119312/',
  },
  {
    id: 83,
    name: '米粉で作った山菜うどん',
    price: 390.96,
    priceAll: 19548,
    count: 50,
    limit: '5年',
    allergy: '',
    genre: '麺類',
    isOnly: false,
    url: 'https://ec.midori-anzen.com/shop/g/g4082112863/',
  },
]
