import { Inter } from 'next/font/google'
import './globals.scss'

import { Header } from '../components/Header'
import GoogleAnalytics from '../components/GoogleAnalytics'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <GoogleAnalytics />
        <Header />
        {children}
      </body>
    </html>
  )
}
